all:
	gcc -g3 -o basic-trace-example basic-trace-example.c -L.. -lqdpll
	#gcc -g3 -o basic-api-example2 basic-api-example2.c -L.. -lqdpll
	#gcc -g3 -o basic-api-example3 basic-api-example3.c -L.. -lqdpll
	#gcc -g3 -o basic-manual-selectors basic-manual-selectors.c -L.. -lqdpll
	#gcc -g3 -o basic-clause-groups-api-example basic-clause-groups-api-example.c -L.. -lqdpll
	#gcc -g3 -o basic-clause-groups-api-example-assumptions basic-clause-groups-api-example-assumptions.c -L.. -lqdpll
	#gcc -g3 -o mus-extraction mus-extraction.c -L.. -lqdpll
	#gcc -g3 -o mus-extraction_test mus-extraction_test.c -L.. -lqdpll
	#gcc -g3 -o mus-extraction_trace mus-extraction_trace.c -L.. -lqdpll
	gcc -g3 -o bug_fixing bug_fixing.c -L.. -lqdpll
	gcc -g3 -o automatic_fuzzy_check automatic_fuzzy_check.c -L.. -lqdpll
	gcc -g3 -o basic-api-example_implementationtest basic-api-example_implementationtest.c -L.. -lqdpll
	#gcc -g3 -o hash_test hash_test.c -L.. -lqdpll
	gcc -g3 -o dep_mus_cluster dep_mus_cluster.c -L.. -lqdpll


